import nico

const

  SCREEN_WIDTH = 128

  BAR_LEN* = 20
  Y_BAR_POS* = 100
  BAR_HEIGTH* = 4

  TARGET_ROWS* = 4
  TARGET_COLS* = 5

  TARGET_WIDTH* = 10
  TARGET_HEIGTH* = 5

  TARGET_PADDING_X* = 10
  TARGET_PADDING_Y* = 10
  
  TARGET_GRID_WIDTH* = (TARGET_COLS * TARGET_WIDTH + (TARGET_COLS - 1) * TARGET_PADDING_X)

  # start points of the grid
  TARGET_GRID_X* = SCREEN_WIDTH /% 2 - TARGET_GRID_WIDTH /% 2
  TARGET_GRID_Y* = 10